### PR TITLE
Creating visual behavior branch

### PR DESCRIPTION
**Pull request by corbennett**

### CODE REVIEW

**Comment by saskiad** [comment]
we need to resolve these conflicts in order to merge

**Comment by saskiad** [comment]
@corbennett these conflicts need to be resolved if we're going to merge this.

**Comment by ceesem** [comment]
These conflicts should be eliminated by using a .gitignore that doesn't include any of the files in `_build`.

**Comment by matchings** [comment]
Corbett says he redid this work in the `visual_behavior` branch

**Pull request closed without merging**
